apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: ServiceName-gateway-mapping
spec:
  gatewayRef:
    name: ServiceName-gateway
  routeConfigRef:
    name: ServiceName-gateway-route
