apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: GatewayName-Route
spec:
  service:
    name: ServiceName
  routes:
  - predicates:
      - Path=/ServiceName/**
    filters:
      - StripPrefix=1
